### ISSUE TITLE
data query problem

### ISSUE THREAD

**Issue by Leibaky** [fboerman/gie-py#3]
Hello!
I tried to download some LNG data using the instruction but everything I got was this: unsupported operand type(s) for I: 'dict' and 'dict'. Could you please help me to solve this issue?

**Comment by fboerman** [comment]
Hi could you please provide a minimal code snippit to showcase the problem? Also which python version are you using?

-------- Original Message --------

**Comment by Leibaky** [comment]
Here is my code:

from gie import GiePandasClient
client = GiePandasClient(api_key='API')
df_terminal=client.query_lng_terminal('zeebrugge', start='2020-01-01', end='2022-07-10')
df_lso=client.query_lng_lso('fluxys_lng', start='2020-01-01', end='2022-07-10')

I am using Python 3.

**Comment by fboerman** [comment]
hi @Leibaky I think the error comes from using python < 3.9. You need at least python 3.9. which version are you using? 3.8?

**Comment by Leibaky** [comment]
Yes, the problem is solved. Thank you!
