### ISSUE TITLE
Gie-py with proxy

### ISSUE THREAD

**Issue by risosoky** [fboerman/gie-py#6]
Hello, is there any way how to use proxy with GiePandasClient? 

Example how it works at Entsog-py:
client = GiePandasClient(api_key=api_key)
client.session.proxies = proxies

Thanks for an answer :)

**Comment by fboerman** [comment]
hi @risosoky  very sorry for the late reply I missed this. Yes you can in the same way! But in this library you need to do client.s.proxies as the sessions object is called diferent in the class. hope that helps!
